### ISSUE TITLE
Error: Cannot find module 'JSON5'

### ISSUE THREAD

**Issue by sabas** [mapbox/mapbox-gl-codeflow-example#2]
I npm installed in the folder and it gives the error in the subject. I tried to install globally both gulp and json5 but the error still persists

**Comment by sabas** [comment]
In gulp-json5 needs to update require('JSON5') to require('json5')
https://github.com/nechtan/gulp-json5/blob/master/index.js#L4

Now it works

**Comment by tmcw** [comment]
Closing; please ticket upstream.
